main:
	gcc -Wall -o server server.c -lpthread
	gcc -Wall -o client client.c -lpthread
	# in server ./server port name
	# in client ./client client_name 0 127.0.0.1 port or client_name 1 name
clean:
	rm server
	rm client
