export PATH := /home/wojlewy/CLionProjects/LewickiWojciech/cw03/zad1:$(PATH)

main:
	gcc -Wall -o main main.c
	./main input.txt
	make clean
	#if you want to see how it fails put this in input.txt: ls +l
clean:
	rm main
