main:
	gcc -Wall -o server server.c
	gcc -Wall -o client client.c
	./server &
	./client input.txt &
	./client input.txt &
	./client input.txt &
	./client input.txt &
	./client input.txt &
	./client input.txt &
	./client input.txt &
	./client input.txt &
	./client input.txt &
	./client input.txt &
	./client input.txt &
	./client input.txt &
	./client endinginput.txt

clean:
	rm server
	rm client	
